#!/usr/bin/env bash
# Phase 13 — Connector breadth: OpenAPI-autogen (primary) + MCP adapter (fallback),
#            both projecting into the existing CapabilityRegistry.
#
# Design:  docs/architecture/mcp-capability-adapter.md
# Build:   docs/handoff/p13-implementation-brief.md
#
# Done when — the increments of the brief, in order:
#   0. Generalize the three F-era converger seams so the catalog is SOURCE-AGNOSTIC:
#      (1) effect from a structural signal the capability declares, NOT an id regex;
#      (2) a deliver-node effect fallback (parity with connector-action);
#      (3) connector-generic destination schema-discovery — also wires native
#          sheets_describe (registered at google/index.js, unwired from the converger).
#   A. Capability contract + OpenAPI adapter (verb→effect, response→locators, enum→domains),
#      behind a mandatory human curation pass.
#   B. Outbound execution + per-tenant auth on the Bearer header — reuses the existing
#      vault / CONNECTOR_INJECTORS; FAIL-CLOSED on missing tenant (no `?? default`).
#   C. MCP adapter (fallback) for OpenAPI-poor services (Linear GraphQL-only; Notion no
#      spec), remote Streamable-HTTP only — never a per-tenant stdio subprocess.
#   D. THE MOAT, adversarial: the P12 moat suite holds with an OpenAPI- AND an MCP-sourced
#      write capability substituted in. NO P12 invariant weakened.
#
# ── WHAT THIS GATE PROVES (calibration — operator, 2026-07-15) ─────────────────
# This gate proves exactly two things, and nothing else blocks the phase close:
#   (1) THE BACKEND WORKS — the behavioral acceptance tests pass (the moat holds,
#       the seams are generalized, a real autogenerated connector reads/writes
#       end-to-end for a tenant, cross-tenant isolation holds).
#   (2) THE UI/UX WORKS for the phase's expected outcome — proven by a LIVE, HEADED
#       browser run the operator can watch (connect a service Atlas never hand-built,
#       build a workflow with it, run it, see the real read/write). This is attested
#       by the verifier in docs/gates/p13.md with saved screenshots (CLAUDE.md,
#       Working rules: visible UI verification). A script cannot drive a headed
#       browser, so this half is a verifier-attested artifact, not an assertion here.
#
# There is deliberately NO aggregate mutation-sweep coverage FLOOR as a blocking bar
# in P13 — that percentage chase is what stalled P12's close over a non-functional
# gap. Mutation-testing stays an INTERNAL builder technique: each new guard must fail
# when its bug is reverted (so the acceptance tests actually bite). The survivor list
# is an informational report, never a pass/fail number. (Decided by the operator,
# 2026-07-15. This is a per-phase calibration, not a weakening of P12's gate.)
#
# This gate is PROGRESSIVE and FAIL-CLOSED. It runs the increments in order and stops at
# the first one that is not done, naming it. So at any point:
#
#     bash scripts/gate.sh 13
#
# answers both "is the phase closed?" and "which increment do I build next?".
# An unimplemented check does NOT pass. Do not weaken a check to force a pass — if a check
# is wrong, fix it and record why in CLAUDE.md (CLAUDE.md, Gates). A diff against this file
# is how a verifier detects gate-weakening; the behavioral checks are ADDED here, never
# removed. (Removing the mutation FLOOR is not a weakening — it was never a P13 bar; the
# BEHAVIORAL and UI/UX proofs are the bar, and those only ratchet up.)
set -eu
cd "$(git rev-parse --show-toplevel)"

fail() { echo "p13 FAIL: $*" >&2; exit 1; }

# `next` = this increment is not built yet. Not a defect — the phase is simply not
# finished. Fail-closed all the same: the gate does not pass.
next() {
  echo "" >&2
  echo "p13: NOT CLOSED — next increment to build: $1" >&2
  echo "     brief: docs/handoff/p13-implementation-brief.md, increment $1" >&2
  echo "     missing: $2" >&2
  exit 1
}

# ── 0. REGRESSION — must hold at EVERY increment, not just at the end ──────────
# P13 must not regress P12. When P13-0 lands, wire the P12 functional suites here
# exactly as p12.sh runs them (control-flow, moat-adversarial, decision-adversarial,
# gate-adversarial, fan-out, example-oracle) + cross-tenant isolation + tier caps.
# The moat (LLM_INPUT_NOT_ENUM) and complete⇒publishable must hold for the NEW
# capability sources too — that is increment D's adversarial gate.
# (Nothing to regress until P13-0 exists; the gate still fails closed below.)

# ── P13-0. The converger seams are generalized (catalog is source-agnostic) ────
# Contract (behavioral, line-independent — see the brief): a SYNTHETIC write capability
# registered with NO code special-casing it must, with zero further changes,
#   (a) classify as a WRITE  → gets an idempotency key + the approval gate fires;
#   (b) as a `deliver` node, SATISFY a record_exists assertion (no false UNSATISFIED_ASSERTION);
#   (c) offer click-to-pick destination resolution via its connector's schema-read capability.
# Each pinned by test-adversary and mutation-killed (revert the seam ⇒ the test goes red).
P130_TEST="tests/converger/source-agnostic-catalog.test.js"
[ -f "$P130_TEST" ] || next "P13-0" \
  "the source-agnostic-catalog adversarial suite ($P130_TEST) does not exist — the three F-era seams (outcome-oracle effect-from-structure, deliver-node effect fallback, connector-generic destinations + sheets_describe wired) are not generalized yet"

# When P13-0 lands, replace the line below with the real run + a mutation-kill of the
# three seam guards, then add the P13-A/B/C/D blocks in order.
next "P13-0" \
  "$P130_TEST exists but the gate's real checks are not wired in — run the suite, mutation-kill the three seam guards, then unblock and add P13-A"

# ── P13-A / P13-B / P13-C / P13-D — added as each increment lands (see the brief) ──
